version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  assignees:
  - danirod
  labels:
  - dependencies
  commit-message:
    prefix: chore
    include: scope
