version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 99
  reviewers:
  - danirod
  assignees:
  - danirod
  labels:
  - dependencies
  commit-message:
    prefix: chore
    include: scope
