name: Android
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build an entire ospDebug flavor
        run: ./gradlew android-osp:assembleDebug --no-daemon
