name: Build
on:
  push:
    branches:
      - master

env:
  # This will be added to GITHUB_RUN_NUMBER to build a version code that continues from where
  # I started bumping the version code and build numbers manually. (Note: sometimes I may
  # subtract 1 from here if a Git push went wrong but I don't want to bump the version code).
  GITHUB_RUN_OFFSET: 192

jobs:
  assembly-information:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.info.outputs.build_number }}
      version: ${{ steps.info.outputs.app_version }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Configure JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Print assembly information
        run: ./gradlew -q core:assemblyInformation
      - name: Store assembly information
        id: info
        run: ./gradlew -q core:assemblyInformationGithub >> "$GITHUB_OUTPUT"
  lwjgl3-jar:
    runs-on: ubuntu-latest
    needs: assembly-information
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Configure JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Compile and package the application
        run: |
          ./gradlew lwjgl3:build
          ./gradlew lwjgl3:jar
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rectball-${{ needs.assembly-information.outputs.version }}-lwjgl3
          path: lwjgl3/build/lib/*.jar
  lwjgl3-darwin-x86_64:
    runs-on: macOS-13
    needs: assembly-information
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Configure JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
        # Note: I am hardcoding the versionFamily to 1.0 because macOS does
        # not allow versions starting with zero on its applications.
      - name: Compile and package the application for macOS
        run: |
          ./gradlew clean
          ./gradlew -PversionFamily=1.0 lwjgl3:jpackageImage
          hdiutil create -volname Rectball -srcfolder lwjgl3/build/jpackage -ov -format UDZO lwjgl3/build/jpackage/rectball.dmg
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rectball-${{ needs.assembly-information.outputs.version }}-darwin-x86_64
          path: lwjgl3/build/jpackage/rectball.dmg
  lwjgl3-darwin-aarch64:
    runs-on: macos-13-xlarge
    needs: assembly-information
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Configure JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
        # Note: I am hardcoding the versionFamily to 1.0 because macOS does
        # not allow versions starting with zero on its applications.
      - name: Compile and package the application for macOS
        run: |
          ./gradlew clean
          ./gradlew -PversionFamily=1.0 lwjgl3:jpackageImage
          hdiutil create -volname Rectball -srcfolder lwjgl3/build/jpackage -ov -format UDZO lwjgl3/build/jpackage/rectball.dmg
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rectball-${{ needs.assembly-information.outputs.version }}-darwin-aarch64
          path: lwjgl3/build/jpackage/rectball.dmg
  lwjgl3-linux-gnu-x86_64:
    runs-on: ubuntu-latest
    needs: assembly-information
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Configure AppImage dependencies
        run: sudo apt-get update && sudo apt-get install -y fuse
      - name: Configure JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Compile and package the application for GNU/Linux
        run: |
          ./gradlew clean
          ./gradlew lwjgl3:build
          scripts/gen-appimage.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rectball-${{ needs.assembly-information.outputs.version }}-linux-gnu-x86_64
          path: lwjgl3/build/rectball*.AppImage
  lwjgl3-winnt-x86_64:
    runs-on: windows-latest
    needs: assembly-information
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Configure JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Compile and package the application for Microsoft Windows NT
        run: |
          $VERSION_ID=$env:GITHUB_SHA.SubString(0, 8)
          .\gradlew.bat clean
          .\gradlew.bat lwjgl3:build
          .\gradlew.bat lwjgl3:jpackageImage
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rectball-${{ needs.assembly-information.outputs.version }}-winnt-x86_64
          path: lwjgl3/build/jpackage
  android:
    runs-on: ubuntu-latest
    needs: assembly-information
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Configure JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Compile Android APK
        run: |
          ./gradlew clean
          ./gradlew android:osp:assembleRelease
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rectball-${{ needs.assembly-information.outputs.version }}-android
          path: android/osp/build/outputs/apk/release/*.apk
  teavm:
    runs-on: ubuntu-latest
    needs: assembly-information
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Configure JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Compile TeaVM
        run: |
          ./gradlew clean
          ./gradlew teavm:build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rectball-${{ needs.assembly-information.outputs.version }}-teavm
          path: teavm/build/dist/webapp
