name: Android
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build an entire ospDebug flavor
        run: ./gradlew assembleOspDebug
      - name: Publish APK as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: rectball-osp-debug.apk
          path: app/build/outputs/apk/osp/debug/android-osp-debug.apk